### PR TITLE
Implements auto-refreshing of access-tokens for clients

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**

### CODE REVIEW

**Comment by FinnStutzenstein** [comment]
It does not work. In the client I still get an `invalid signature` -> The PR is not rebased on the current master. Are you sure that you used the right keys? Please validate, that your keys have the right md5 checksum in the container:

```
md5sum /tmp/keys/*

a28d6e145813cb92621b43578b7dd99a  rsa-cookie.key
c279133b021e731a403bcdeb28a86361  rsa-cookie.key.pub
2ee409a64def14adb3c0c4bb82d5ae4c  rsa-token.key
614d52f6a1598951c064af2c5875fbe6  rsa-token.key.pub
```

**Comment by GabrielInTheWorld** [comment]
Sorry, please try again.

**Comment by FinnStutzenstein** [comment]
This looks good. I get a stacktrace in the console, but it all works fine. I guess it is just printed somewhere, where it can be removed. Can you fix this?

```
auth_1              | [11.08.2020 -- 13:50:19]: Verify token failured:  TokenExpiredError: jwt expired
auth_1              |     at /app/node_modules/jsonwebtoken/verify.js:152:21
auth_1              |     at getSecret (/app/node_modules/jsonwebtoken/verify.js:90:14)
auth_1              |     at Object.module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:94:10)
auth_1              |     at TicketService.verifyToken (/app/src/api/services/ticket-service.ts:46:29)
auth_1              |     at TicketService.<anonymous> (/app/src/api/services/ticket-service.ts:109:34)
auth_1              |     at Generator.next (<anonymous>)
auth_1              |     at /app/node_modules/tslib/tslib.js:115:75
auth_1              |     at new Promise (<anonymous>)
auth_1              |     at Object.__awaiter (/app/node_modules/tslib/tslib.js:111:16)
auth_1              |     at TicketService.validateTicket (/app/src/api/services/ticket-service.ts:94:24) {
auth_1              |   expiredAt: 2020-08-11T12:47:04.000Z
auth_1              | }
```

**Comment by GabrielInTheWorld** [comment]
Yes, of course. I have left it, because I thought it would be nice to debug. ;)

**Comment by GabrielInTheWorld** [comment]
I remove this debug-message and merge it into the repo.

**Pull request merged**
